### ISSUE TITLE
[サイコロ]サイコロアニメーションの作成

### ISSUE THREAD

**Issue by yKicchan** [YutaKohashi/Spajam2017#2]
## 以下素材(要透過！)
![default](https://cloud.githubusercontent.com/assets/27273218/25305376/131cddb4-27b5-11e7-98a6-4ed03f6a6070.gif)
![dice1](https://cloud.githubusercontent.com/assets/27273218/25305377/166c2a06-27b5-11e7-84be-f519c176bd56.png)
![dice2](https://cloud.githubusercontent.com/assets/27273218/25305378/1691af2e-27b5-11e7-8296-c176d43735a7.png)
![dice3](https://cloud.githubusercontent.com/assets/27273218/25305379/169bc630-27b5-11e7-80c4-04860c063591.png)
![dice4](https://cloud.githubusercontent.com/assets/27273218/25305381/16a0e43a-27b5-11e7-86fa-40686c64f333.png)
![dice5](https://cloud.githubusercontent.com/assets/27273218/25305380/16a0db48-27b5-11e7-88a8-265109a240e6.png)
![dice6](https://cloud.githubusercontent.com/assets/27273218/25305382/16a449cc-27b5-11e7-8a76-3cb4a88021a1.png)

**Comment by yothio** [comment]
![dice_anime](https://cloud.githubusercontent.com/assets/11973775/25307323/1b71e44e-27da-11e7-8b64-4be507a606e2.gif)
